# navsat_config.yaml

navsat_transform_node:
  ros__parameters:
    
    frequency: 30.0
    delay: 0.0011 
    transform_timeout: 0.2 
    magnetic_declination_radians: 0.0           
    zero_altitude: true                
    broadcast_cartesian_transform: false
    broadcast_utm_transform: true
    broadcast_utm_transform_as_parent_frame_: true
    publish_filtered_gps: true          
    use_odometry_yaw: true             
    wait_for_datum: false       
    use_sim_time: false        